backend:
  name: github
  repo: jerrylabs/kamenoranc
  site_domain: rainbow-meringue-7cdef4
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: posts
    label: Články
    create: true
    slug: {{slug}}
    format: yaml-frontmatter
    folder: content/blog
    fields:
    - {label: "Titulek", name: "title", widget: "string"}
    - {label: "Datum", name: "date", widget: "datetime"}
    - {label: "Popis", name: "description", widget: "string", required: false}
    - {label: "Text", name: "body", widget: "markdown", comment: 'This is a multiline\ncomment' }
